import type { FolderItem, FileItem } from './types'

export const MOCK_FOLDERS: FolderItem[] = [
  { id: 'root',             name: '전체 자료',    parentId: null },
  { id: 'worship',          name: '예배부',        parentId: 'root' },
  { id: 'worship-bulletin', name: '주보',          parentId: 'worship' },
  { id: 'worship-order',    name: '예배 순서지',   parentId: 'worship' },
  { id: 'worship-forms',    name: '양식',          parentId: 'worship' },
  { id: 'praise',           name: '찬양팀',        parentId: 'root' },
  { id: 'praise-scores',    name: '악보',          parentId: 'praise' },
  { id: 'praise-audio',     name: '음원',          parentId: 'praise' },
  { id: 'education',        name: '교육부',        parentId: 'root' },
  { id: 'education-sunday', name: '주일학교',      parentId: 'education' },
  { id: 'education-bible',  name: '성경공부',      parentId: 'education' },
  { id: 'youth',            name: '청년부',        parentId: 'root' },
  { id: 'youth-retreat',    name: '수련회',        parentId: 'youth' },
  { id: 'youth-meeting',    name: '모임 자료',     parentId: 'youth' },
  { id: 'admin',            name: '행정부',        parentId: 'root' },
  { id: 'admin-budget',     name: '예산',          parentId: 'admin' },
  { id: 'admin-minutes',    name: '회의록',        parentId: 'admin' },
]

export const MOCK_FILES: FileItem[] = [
  {
    id: '1',
    name: '2026년 8월 4주 주보.pdf',
    mimeType: 'application/pdf',
    size: 2.4 * 1024 * 1024,
    folderId: 'worship-bulletin',
    uploadedBy: '김성진',
    updatedAt: '2026-08-31T09:00:00',
    starred: true,
    tags: ['주보', '예배'],
    description: '8월 마지막 주 주보입니다.',
  },
  {
    id: '2',
    name: '2026년 8월 3주 주보.pdf',
    mimeType: 'application/pdf',
    size: 2.2 * 1024 * 1024,
    folderId: 'worship-bulletin',
    uploadedBy: '김성진',
    updatedAt: '2026-08-24T08:00:00',
    starred: false,
    tags: ['주보', '예배'],
  },
  {
    id: '3',
    name: '예배 순서지 양식.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 0.3 * 1024 * 1024,
    folderId: 'worship-forms',
    uploadedBy: '김성진',
    updatedAt: '2026-08-20T13:00:00',
    starred: true,
    tags: ['예배', '양식'],
  },
  {
    id: '4',
    name: '8월 찬양 악보 모음.pdf',
    mimeType: 'application/pdf',
    size: 5.2 * 1024 * 1024,
    folderId: 'praise-scores',
    uploadedBy: '최지민',
    updatedAt: '2026-08-27T16:00:00',
    starred: true,
    tags: ['악보', '찬양'],
  },
  {
    id: '5',
    name: '9월 찬양 선곡 리스트.docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 0.2 * 1024 * 1024,
    folderId: 'praise',
    uploadedBy: '최지민',
    updatedAt: '2026-08-15T10:00:00',
    starred: false,
    tags: ['찬양', '선곡'],
  },
  {
    id: '6',
    name: '찬양팀 연습 음원.mp3',
    mimeType: 'audio/mpeg',
    size: 8.1 * 1024 * 1024,
    folderId: 'praise-audio',
    uploadedBy: '최지민',
    updatedAt: '2026-07-25T18:00:00',
    starred: false,
    tags: ['찬양', '음원'],
  },
  {
    id: '7',
    name: '주일학교 9월 공과표.pptx',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    size: 3.1 * 1024 * 1024,
    folderId: 'education-sunday',
    uploadedBy: '정수아',
    updatedAt: '2026-08-26T10:00:00',
    starred: false,
    tags: ['주일학교', '교육'],
  },
  {
    id: '8',
    name: '어린이부 8월 공과 사진.jpg',
    mimeType: 'image/jpeg',
    size: 4.5 * 1024 * 1024,
    folderId: 'education-sunday',
    uploadedBy: '정수아',
    updatedAt: '2026-08-11T12:00:00',
    starred: false,
    tags: ['교육', '사진'],
  },
  {
    id: '9',
    name: '2026 여름 수련회 포스터.png',
    mimeType: 'image/png',
    size: 1.8 * 1024 * 1024,
    folderId: 'youth-retreat',
    uploadedBy: '이지현',
    updatedAt: '2026-08-30T14:30:00',
    starred: false,
    tags: ['수련회', '포스터'],
  },
  {
    id: '10',
    name: '청년부 수련회 명단.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 0.4 * 1024 * 1024,
    folderId: 'youth-retreat',
    uploadedBy: '이지현',
    updatedAt: '2026-07-20T11:00:00',
    starred: false,
    tags: ['수련회', '청년부'],
  },
  {
    id: '11',
    name: '청년부 8월 모임 영상.mp4',
    mimeType: 'video/mp4',
    size: 450 * 1024 * 1024,
    folderId: 'youth-meeting',
    uploadedBy: '이지현',
    updatedAt: '2026-08-24T20:00:00',
    starred: false,
    tags: ['영상', '청년부'],
  },
  {
    id: '12',
    name: '2026 하반기 예산안.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 0.5 * 1024 * 1024,
    folderId: 'admin-budget',
    uploadedBy: '박민수',
    updatedAt: '2026-08-28T11:00:00',
    starred: false,
    tags: ['예산', '행정'],
  },
  {
    id: '13',
    name: '2026 여름 수련회 결산.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 0.8 * 1024 * 1024,
    folderId: 'admin-budget',
    uploadedBy: '박민수',
    updatedAt: '2026-08-18T15:00:00',
    starred: false,
    tags: ['수련회', '결산'],
  },
  {
    id: '14',
    name: '2026년 사역 계획서.pptx',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    size: 6.3 * 1024 * 1024,
    folderId: 'admin',
    uploadedBy: '박민수',
    updatedAt: '2026-07-30T09:00:00',
    starred: true,
    tags: ['계획', '사역'],
  },
  {
    id: '15',
    name: '2026 교회 사진 모음.zip',
    mimeType: 'application/zip',
    size: 128 * 1024 * 1024,
    folderId: 'admin',
    uploadedBy: '박민수',
    updatedAt: '2026-08-25T09:30:00',
    starred: false,
    tags: ['사진'],
  },
]
